DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats(
    id bigint generated by default as identity primary key,
    app varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    ip varchar(32) NOT NULL,
    created timestamp NOT NULL
);